### ISSUE TITLE
Missing electronics info

### ISSUE THREAD

**Issue by DaveWW00** [HelgeKeck/rome#2]
Can you please add info to the readme of what motor driver and endstops you have each extruder or sensor connected to?  Directions dont include any information or photos on the hardware side of things except for the y-splitter.  I think all of this would help more folks to utilize this.

**Comment by HelgeKeck** [comment]
you can use any driver that works for your extruder and conenct the endstoips to any gpio pins you have available

**Comment by HelgeKeck** [comment]
ther are no rules for that
